name: mensa
description: "The mensa package"
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  core:
    path: ../../core 
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

 
