name: mensa
description: "The mensa package"
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  core:
    path: ../../core 
  shared_api:
    path: ../../shared_api
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  http: ^1.2.2
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.7
  permission_handler: ^11.3.1
  flutter_lucide: ^1.2.0
  get_it: ^8.0.1  
  flutter_svg: ^2.0.9
  collection: ^1.18.0
  scrollable_positioned_list: ^0.3.8
  skeletonizer: ^1.4.2
  flutter_native_splash: ^2.3.1
  share_plus: ^10.1.2
  flutter_sticky_header: ^0.7.0
  modal_bottom_sheet: ^3.0.0
  expandable_page_view: ^1.0.17
  geolocator: ^14.0.0
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  scrollview_observer: ^1.25.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  go_router_builder: ^2.7.1
  build_runner: any
  build_verify: any


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dish_category/


 
