name: "cinema"
description: "The cinema package"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  core_routes:
    path: ../../core_routes
  shared_api:
    path: ../../shared_api
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  http: ^1.2.2
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.7
  flutter_lucide: ^1.2.0
  get_it: ^8.0.1
  intl: any
  share_plus: ^10.1.2
  skeletonizer: ^1.4.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: any
  build_verify: any
