name: lmu_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_bloc: ^8.1.3
  provider: ^6.1.2
  core:
    path: ./core
  mensa: 
    path: ./feature_modules/mensa
  settings: 
    path: ./feature_modules/settings
  wunschkonzert:
    path: ./feature_modules/wunschkonzert
  http: ^0.13.3
  flutter_lucide: ^1.2.0
  collection: ^1.15.0
  get_it: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.7.1
  build_runner: any
  build_verify: any


flutter:
  uses-material-design: true

