name: lmu_app
description: "LMU Students - Your Companion for Study and Campus Life at LMU Munich"
publish_to: "none"
version: 1.1.1+15

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: 15.1.3
  flutter_bloc: ^8.1.3
  core:
    path: ./core
  core_routes:
    path: ./core_routes
  home:
    path: ./feature_modules/home
  cinema:
    path: ./feature_modules/cinema
  mensa:
    path: ./feature_modules/mensa
  explore:
    path: ./feature_modules/explore
  settings:
    path: ./feature_modules/settings
  wishlist:
    path: ./feature_modules/wishlist
  feedback:
    path: ./feature_modules/feedback
  user:
    path: ./feature_modules/user
  sports:
    path: ./feature_modules/sports
  timeline:
    path: ./feature_modules/timeline
  roomfinder:
    path: ./feature_modules/roomfinder
  libraries:
    path: ./feature_modules/libraries
  benefits:
    path: ./feature_modules/benefits
  launch_flow:
    path: ./feature_modules/launch_flow
  studies:
    path: ./feature_modules/studies
  calendar:
    path: ./feature_modules/calendar
  lectures:
    path: ./feature_modules/lectures
  people:
    path: ./feature_modules/people
  shared_api:
    path: ./shared_api

  shared_preferences: ^2.0.7
  flutter_lucide: ^1.2.0
  collection: ^1.18.0
  get_it: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.3.1
  animated_reorderable_list: ^1.3.0
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_lints: ^4.0.0
  go_router_builder: ^2.9.0
  json_serializable: ^6.6.2
  build_runner: any
  husky: ^0.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - core/lib/assets/
    - feature_modules/mensa/assets/
    - feature_modules/explore/assets/
  shaders:
    - assets/shader/light_rays.frag
