name: lmu_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: any
  flutter_bloc: ^8.1.3
  provider: ^6.1.2
  core:
    path: ./core
  mensa: 
    path: ./feature_modules/mensa
  explore:
    path: ./feature_modules/explore
  settings: 
    path: ./feature_modules/settings
  wunschkonzert:
    path: ./feature_modules/wunschkonzert
  http: ^0.13.3
  mapbox_maps_flutter: ^2.2.0
  permission_handler: ^11.3.1
  flutter_lucide: ^1.2.0
  collection: ^1.18.0
  get_it: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  tuple: ^2.0.2
  flutter_svg: ^2.0.9
  soft_edge_blur: ^0.1.3
  fluttertoast: ^8.2.8
  scrollable_positioned_list: ^0.3.8
  super_cupertino_navigation_bar: ^2.1.2
  skeletonizer: ^1.4.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.7.1
  build_runner: any
  build_verify: any
  husky: ^0.1.7


flutter:
  uses-material-design: true
  generate: true 

