name: lmu_app
description: "LMU Students - a mobile app for and from students"
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.2
  go_router: any
  flutter_bloc: ^8.1.3
  provider: ^6.1.2
  core:
    path: ./core
  home:
    path: ./feature_modules/home
  mensa:
    path: ./feature_modules/mensa
  explore:
    path: ./feature_modules/explore
  settings:
    path: ./feature_modules/settings
  wishlist:
    path: ./feature_modules/wishlist
  feedback:
    path: ./feature_modules/feedback
  user:
    path: ./feature_modules/user
  shared_api:
    path: ./shared_api
  http: ^1.2.2
  mapbox_maps_flutter: ^2.5.0
  shared_preferences: ^2.0.7
  geolocator: ^13.0.2
  flutter_lucide: ^1.2.0
  lucide_icons_svg: ^0.0.4
  collection: ^1.18.0
  get_it: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  tuple: ^2.0.2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.8
  scrollable_positioned_list: ^0.3.8
  skeletonizer: ^1.4.2
  flutter_native_splash: ^2.3.1
  share_plus: ^10.1.2
  in_app_review: ^2.0.10
  flutter_sticky_header: ^0.7.0
  nested_scroll_view_plus: ^2.0.0
  expandable_page_view: ^1.0.17
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  json_serializable: ^6.6.2
  build_runner: any
  build_verify: any
  husky: ^0.1.7


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - core/lib/assets/
    - feature_modules/mensa/assets/
    - feature_modules/explore/assets/

