name: core_routes
description: "Contains app routes."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  go_router: ^15.1.0
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_lucide: ^1.2.0
  get_it: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_verify: any
  go_router_builder: ^2.9.0
