name: "benefits"
description: "The benefits package"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  core_routes:
    path: ../../core_routes
  shared_api:
    path: ../../shared_api
  get_it: ^8.0.1
  http: ^1.2.2
  json_annotation: ^4.0.1
  flutter_lucide: ^1.2.0
  widget_driver: ^1.0.10
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  widget_driver_generator: ^1.3.3
