name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^15.1.0
  go_router_builder: ^2.9.0
  get_it: ^8.0.1
  flutter_lucide: ^1.2.0
  lucide_icons_svg: ^0.0.4
  shared_api:
    path: ../../shared_api
  json_annotation: ^4.8.1
  flutter_sticky_header: ^0.7.0
  animated_reorderable_list: ^1.1.5
  skeletonizer: ^1.4.2
  intl: any

  http: any
  collection: ^1.18.0
  shared_preferences: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  build_verify: any
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
