name: core
description: "The core functionality of the project"
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_lucide: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  tuple: ^2.0.2
  modal_bottom_sheet: ^3.0.0
  sprung: ^3.0.1
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  skeletonizer: ^1.4.2
  snap_scroll_physics: ^0.0.1+3
  lucide_icons_svg: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: packages/core/fonts/inter/Inter-Regular.ttf
        - asset: packages/core/fonts/inter/Inter-SemiBold.ttf
          weight: 700
