name: core
description: "The core functionality of the project"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_lucide: ^1.2.0
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1
  json_annotation: ^4.0.1
  intl: any
  tuple: ^2.0.2
  modal_bottom_sheet: ^3.0.0
  sprung: ^3.0.1
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  skeletonizer: ^1.4.2
  snap_scroll_physics: ^0.0.1+3
  lucide_icons_svg: ^0.0.4
  collection: ^1.18.0
  flutter_sticky_header: ^0.7.0
  nested_scroll_view_plus: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  lottie: ^2.7.0
  http: ^1.2.2
  path_provider: ^2.1.5
  logging: ^1.3.0
  get_it: ^8.0.3
  go_router: ^14.3.0
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: any
  build_verify: any

flutter:
  generate: true
  assets:
    - lib/assets/
  fonts:
    - family: Inter
      fonts:
        - asset: packages/core/fonts/inter/Inter-Regular.ttf
        - asset: packages/core/fonts/inter/Inter-SemiBold.ttf
          weight: 700
