name: user
description: Package containing all user related features
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core 
  shared_api:
    path: ../../shared_api
  get_it: ^8.0.1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.2
  build_runner: any

