name: settings
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core 
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^15.1.0
  get_it: ^8.0.1
  shared_api:
    path: ../../shared_api
  flutter_lucide: ^1.6.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.9.0
  build_runner: any
  build_verify: any

