name: settings
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core 
  core_routes:
    path: ../../core_routes
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^8.0.1
  shared_api:
    path: ../../shared_api
  flutter_lucide: ^1.6.1
  share_plus: ^10.1.3
  widget_driver: ^1.0.10
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.1

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.4.9
  widget_driver_generator: ^1.3.3

