// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXahssKRYblX3cGXctP8AKd_Fo64sfzXQ',
    appId: '1:920408486226:web:d4587ba3622783d5cb4a8b',
    messagingSenderId: '920408486226',
    projectId: 'lmu-app-68d2d',
    authDomain: 'lmu-app-68d2d.firebaseapp.com',
    storageBucket: 'lmu-app-68d2d.firebasestorage.app',
    measurementId: 'G-8SNX41LMNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNUgIO6NGirVgflInRBpjEpB3VBxYl5I',
    appId: '1:920408486226:android:e4f7c6ac516612c1cb4a8b',
    messagingSenderId: '920408486226',
    projectId: 'lmu-app-68d2d',
    storageBucket: 'lmu-app-68d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADo3WH7Sf8pFs9JnkdFagQ5VkTP572_cQ',
    appId: '1:920408486226:ios:a4e57d775268dc12cb4a8b',
    messagingSenderId: '920408486226',
    projectId: 'lmu-app-68d2d',
    storageBucket: 'lmu-app-68d2d.firebasestorage.app',
    iosBundleId: 'com.example.lmuApp.RunnerTests',
  );
}
