name: explore
description: "The explore package containing everything which can be explored on a map."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.1
  flutter_svg: ^2.0.17
  flutter_lucide: ^1.2.0
  shared_preferences: ^2.0.7
  geolocator: ^14.0.0
  core:
    path: ../../core
  core_routes:
    path: ../../core_routes
  shared_api:
    path: ../../shared_api
  flutter_map: ^8.1.1  
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.5
  flutter_map_location_marker: ^10.1.0
  flutter_map_animations: ^0.9.0
  collection: ^1.18.0
  widget_driver: ^1.0.10
  http_cache_hive_store: ^5.0.1
  flutter_map_cache: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.6.2
  widget_driver_generator: ^1.3.3

flutter:
  assets:
    - assets/
