#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

dart format . --line-length 120 && dart fix --apply && flutter analyze lib/ test/ --no-cache --verbose | tee result.log | grep -qv 'warning\|error' && echo 'No issues found' || { echo 'Flutter analyze found warnings or errors. Please fix them before pushing.'; exit 1; }
